### ISSUE TITLE
Files not processing when callibrations taken in the morning

### ISSUE THREAD

**Issue by gannonjs** [Keck-DataReductionPipelines/KCWI_DRP#149]
I am currently running the pipeline (kcrm_merge branch) and have noted that I need to do the

```reduce_kcwi -f kr*.fits -c ./kcwi_editted.cfg --red```

Call twice to properly reduce the data. On the first run it jumps through the science files and says no calibrations found and so skips them, then it finds the calibration, reduces them but does not return to the science files. The second running of this the reduced calibrations exist and so it is able to reduce the data. 

Note: we were second half observers and had to run morning cals. As such our cals all have higher kb000XX number than the actual science data.

**Comment by scizen9** [comment]
You need the -g or --group parameter, otherwise, it will just try to run them in sequence.  The group parameter tells the pipeline to ingest all the files, then groups them and processes them in the order the DRP needs.  The way you are running it, it wouldn't know what to do with your science files on the first pass.
