### ISSUE TITLE
Unable to create MasterSky with 1.1.0 update

### ISSUE THREAD

**Issue by rremigio** [Keck-DataReductionPipelines/KCWI_DRP#159]
I am trying to reduce KCRM data with the recent run using the recent 1.1.0 update to the pipeline. I run into this issue I have encountered before when MakeMasterSky is called when the DRP reaches the standard star observation:

![image](https://github.com/Keck-DataReductionPipelines/KCWI_DRP/assets/42788999/3b947416-6e7e-45a5-957b-02fb0c44646c)

However, if I attempt the same reduction using a relatively recent commit of the `kcrm_merge` branch, MakeMasterSky completes and I am able to continue up to the flux calibration steps

![image](https://github.com/Keck-DataReductionPipelines/KCWI_DRP/assets/42788999/361f0712-fc8a-4953-a18b-3c1c7b71b25f)

**Comment by rremigio** [comment]
I think I am running on the 35fbcb9d72d6a66d747486848dee0268f62d3acc commit from October 6; I think the .py files in my installation are missing changes from Oct 13 onwards.

**Comment by scizen9** [comment]
I am unable to reproduce this error with the 1.1.0 version I have on my machine.  This could be due to three things:

1. In order to get a good wavelength solution, I had to use -M 0.5 on the command line
2. I used the internal continuum flat for the observation
3. I only reduced kr231104_00047.fits and did not combine it with the other std. observations

I have seen this error in the past, but it was always due to some problem with the data, in this case, it may be a bad wavelength solution.  If you can display the kr231104_00024_2d.fits file and see how wiggly it is, that will tell you if the solution was good or not.  You should see the arc lines as straight, without wiggles.

Otherwise, let me know the full reduction sequence for that standard: what flat did you use? Did you combine the three observations?  Did you tweak the wavelength parameters to get a good wavelength solution?

**Comment by rremigio** [comment]
Thank you, I ended up taking your advice and set `MIDFRAC = 0.5` within the .cfg file. That more or less fixed the problem, and the`icube_2d` files look fine.
